export const CURRENCIES = [
  { country: "Afghanistan", code: "AFN", symbol: "؋", name: "Afghan Afghani" },
  { country: "Algeria", code: "DZD", symbol: "DA", name: "Algerian Dinar" },
  { country: "Angola", code: "AOA", symbol: "Kz", name: "Angolan Kwanza" },
  { country: "Argentina", code: "ARS", symbol: "AR$", name: "Argentine Peso" },
  { country: "Armenia", code: "AMD", symbol: "֏", name: "Armenian Dram" },
  { country: "Australia", code: "AUD", symbol: "A$", name: "Australian Dollar" },
  { country: "Austria", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Azerbaijan", code: "AZN", symbol: "₼", name: "Azerbaijani Manat" },
  { country: "Bahrain", code: "BHD", symbol: "BD", name: "Bahraini Dinar" },
  { country: "Bangladesh", code: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
  { country: "Barbados", code: "BBD", symbol: "Bds$", name: "Barbadian Dollar" },
  { country: "Belarus", code: "BYN", symbol: "Br", name: "Belarusian Ruble" },
  { country: "Belgium", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Belize", code: "BZD", symbol: "BZ$", name: "Belize Dollar" },
  { country: "Bhutan", code: "BTN", symbol: "Nu", name: "Bhutanese Ngultrum" },
  { country: "Bolivia", code: "BOB", symbol: "Bs", name: "Bolivian Boliviano" },
  { country: "Botswana", code: "BWP", symbol: "P", name: "Botswana Pula" },
  { country: "Brazil", code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { country: "Brunei", code: "BND", symbol: "B$", name: "Brunei Dollar" },
  { country: "Bulgaria", code: "BGN", symbol: "лв", name: "Bulgarian Lev" },
  { country: "Cambodia", code: "KHR", symbol: "៛", name: "Cambodian Riel" },
  { country: "Cameroon", code: "XAF", symbol: "Fr", name: "Central African CFA" },
  { country: "Canada", code: "CAD", symbol: "CA$", name: "Canadian Dollar" },
  { country: "Chile", code: "CLP", symbol: "CL$", name: "Chilean Peso" },
  { country: "China", code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { country: "Colombia", code: "COP", symbol: "CO$", name: "Colombian Peso" },
  { country: "Costa Rica", code: "CRC", symbol: "₡", name: "Costa Rican Colón" },
  { country: "Croatia", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Cuba", code: "CUP", symbol: "CU$", name: "Cuban Peso" },
  { country: "Cyprus", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Czech Republic", code: "CZK", symbol: "Kč", name: "Czech Koruna" },
  { country: "Denmark", code: "DKK", symbol: "kr", name: "Danish Krone" },
  { country: "Dominican Republic", code: "DOP", symbol: "RD$", name: "Dominican Peso" },
  { country: "Ecuador", code: "USD", symbol: "$", name: "US Dollar" },
  { country: "Egypt", code: "EGP", symbol: "E£", name: "Egyptian Pound" },
  { country: "El Salvador", code: "USD", symbol: "$", name: "US Dollar" },
  { country: "Estonia", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Ethiopia", code: "ETB", symbol: "Br", name: "Ethiopian Birr" },
  { country: "European Union", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Fiji", code: "FJD", symbol: "FJ$", name: "Fijian Dollar" },
  { country: "Finland", code: "EUR", symbol: "€", name: "Euro" },
  { country: "France", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Georgia", code: "GEL", symbol: "₾", name: "Georgian Lari" },
  { country: "Germany", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Ghana", code: "GHS", symbol: "₵", name: "Ghanaian Cedi" },
  { country: "Greece", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Guatemala", code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal" },
  { country: "Guyana", code: "GYD", symbol: "GY$", name: "Guyanese Dollar" },
  { country: "Haiti", code: "HTG", symbol: "G", name: "Haitian Gourde" },
  { country: "Honduras", code: "HNL", symbol: "L", name: "Honduran Lempira" },
  { country: "Hong Kong", code: "HKD", symbol: "HK$", name: "Hong Kong Dollar" },
  { country: "Hungary", code: "HUF", symbol: "Ft", name: "Hungarian Forint" },
  { country: "Iceland", code: "ISK", symbol: "kr", name: "Icelandic Króna" },
  { country: "India", code: "INR", symbol: "₹", name: "Indian Rupee" },
  { country: "Indonesia", code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { country: "Iran", code: "IRR", symbol: "﷼", name: "Iranian Rial" },
  { country: "Iraq", code: "IQD", symbol: "ع.د", name: "Iraqi Dinar" },
  { country: "Ireland", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Israel", code: "ILS", symbol: "₪", name: "Israeli Shekel" },
  { country: "Italy", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Ivory Coast", code: "XOF", symbol: "Fr", name: "West African CFA" },
  { country: "Jamaica", code: "JMD", symbol: "J$", name: "Jamaican Dollar" },
  { country: "Japan", code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { country: "Jordan", code: "JOD", symbol: "JD", name: "Jordanian Dinar" },
  { country: "Kazakhstan", code: "KZT", symbol: "₸", name: "Kazakhstani Tenge" },
  { country: "Kenya", code: "KES", symbol: "KSh", name: "Kenyan Shilling" },
  { country: "Kuwait", code: "KWD", symbol: "KD", name: "Kuwaiti Dinar" },
  { country: "Laos", code: "LAK", symbol: "₭", name: "Lao Kip" },
  { country: "Latvia", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Lebanon", code: "LBP", symbol: "L£", name: "Lebanese Pound" },
  { country: "Libya", code: "LYD", symbol: "LD", name: "Libyan Dinar" },
  { country: "Lithuania", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Luxembourg", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Malaysia", code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { country: "Maldives", code: "MVR", symbol: "Rf", name: "Maldivian Rufiyaa" },
  { country: "Malta", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Mauritius", code: "MUR", symbol: "Rs", name: "Mauritian Rupee" },
  { country: "Mexico", code: "MXN", symbol: "MX$", name: "Mexican Peso" },
  { country: "Mongolia", code: "MNT", symbol: "₮", name: "Mongolian Tögrög" },
  { country: "Morocco", code: "MAD", symbol: "MAD", name: "Moroccan Dirham" },
  { country: "Mozambique", code: "MZN", symbol: "MT", name: "Mozambican Metical" },
  { country: "Myanmar", code: "MMK", symbol: "K", name: "Myanmar Kyat" },
  { country: "Namibia", code: "NAD", symbol: "N$", name: "Namibian Dollar" },
  { country: "Nepal", code: "NPR", symbol: "Rs", name: "Nepalese Rupee" },
  { country: "Netherlands", code: "EUR", symbol: "€", name: "Euro" },
  { country: "New Zealand", code: "NZD", symbol: "NZ$", name: "New Zealand Dollar" },
  { country: "Nicaragua", code: "NIO", symbol: "C$", name: "Nicaraguan Córdoba" },
  { country: "Nigeria", code: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { country: "North Korea", code: "KPW", symbol: "₩", name: "North Korean Won" },
  { country: "Norway", code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { country: "Oman", code: "OMR", symbol: "﷼", name: "Omani Rial" },
  { country: "Pakistan", code: "PKR", symbol: "₨", name: "Pakistani Rupee" },
  { country: "Panama", code: "USD", symbol: "$", name: "US Dollar" },
  { country: "Papua New Guinea", code: "PGK", symbol: "K", name: "Kina" },
  { country: "Paraguay", code: "PYG", symbol: "₲", name: "Paraguayan Guaraní" },
  { country: "Peru", code: "PEN", symbol: "S/", name: "Peruvian Sol" },
  { country: "Philippines", code: "PHP", symbol: "₱", name: "Philippine Peso" },
  { country: "Poland", code: "PLN", symbol: "zł", name: "Polish Złoty" },
  { country: "Portugal", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Qatar", code: "QAR", symbol: "QR", name: "Qatari Riyal" },
  { country: "Romania", code: "RON", symbol: "lei", name: "Romanian Leu" },
  { country: "Russia", code: "RUB", symbol: "₽", name: "Russian Ruble" },
  { country: "Rwanda", code: "RWF", symbol: "RF", name: "Rwandan Franc" },
  { country: "Samoa", code: "WST", symbol: "WS$", name: "Samoan Tālā" },
  { country: "Saudi Arabia", code: "SAR", symbol: "﷼", name: "Saudi Riyal" },
  { country: "Senegal", code: "XOF", symbol: "Fr", name: "West African CFA" },
  { country: "Serbia", code: "RSD", symbol: "din", name: "Serbian Dinar" },
  { country: "Singapore", code: "SGD", symbol: "S$", name: "Singapore Dollar" },
  { country: "Slovakia", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Slovenia", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Solomon Islands", code: "SBD", symbol: "SI$", name: "Solomon Islands Dollar" },
  { country: "Somalia", code: "SOS", symbol: "Sh", name: "Somali Shilling" },
  { country: "South Africa", code: "ZAR", symbol: "R", name: "South African Rand" },
  { country: "South Korea", code: "KRW", symbol: "₩", name: "South Korean Won" },
  { country: "Spain", code: "EUR", symbol: "€", name: "Euro" },
  { country: "Sri Lanka", code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
  { country: "Sudan", code: "SDG", symbol: "ج.س", name: "Sudanese Pound" },
  { country: "Suriname", code: "SRD", symbol: "Sr$", name: "Surinamese Dollar" },
  { country: "Sweden", code: "SEK", symbol: "kr", name: "Swedish Krona" },
  { country: "Switzerland", code: "CHF", symbol: "Fr", name: "Swiss Franc" },
  { country: "Taiwan", code: "TWD", symbol: "NT$", name: "New Taiwan Dollar" },
  { country: "Tanzania", code: "TZS", symbol: "TSh", name: "Tanzanian Shilling" },
  { country: "Thailand", code: "THB", symbol: "฿", name: "Thai Baht" },
  { country: "Timor-Leste", code: "USD", symbol: "$", name: "US Dollar" },
  { country: "Tonga", code: "TOP", symbol: "T$", name: "Tongan Paʻanga" },
  { country: "Trinidad and Tobago", code: "TTD", symbol: "TT$", name: "Trinidad Dollar" },
  { country: "Tunisia", code: "TND", symbol: "DT", name: "Tunisian Dinar" },
  { country: "Turkey", code: "TRY", symbol: "₺", name: "Turkish Lira" },
  { country: "Uganda", code: "UGX", symbol: "USh", name: "Ugandan Shilling" },
  { country: "Ukraine", code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" },
  { country: "United Arab Emirates", code: "AED", symbol: "د.إ", name: "UAE Dirham" },
  { country: "United Kingdom", code: "GBP", symbol: "£", name: "British Pound" },
  { country: "United States", code: "USD", symbol: "$", name: "US Dollar" },
  { country: "Uruguay", code: "UYU", symbol: "UY$", name: "Uruguayan Peso" },
  { country: "Uzbekistan", code: "UZS", symbol: "so'm", name: "Uzbekistani Soum" },
  { country: "Vanuatu", code: "VUV", symbol: "Vt", name: "Vanuatu Vatu" },
  { country: "Venezuela", code: "VES", symbol: "Bs", name: "Venezuelan Bolívar" },
  { country: "Vietnam", code: "VND", symbol: "₫", name: "Vietnamese Dong" },
  { country: "Zambia", code: "ZMW", symbol: "ZK", name: "Zambian Kwacha" },
  { country: "Zimbabwe", code: "ZWL", symbol: "Z$", name: "Zimbabwean Dollar" },
]
