import Link from 'next/link'
import { ArrowLeft, Sparkles } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background font-josefin text-foreground/90 selection:bg-primary/30 selection:text-white">
      {/* Background Polish */}
      <div className="fixed inset-0 pointer-events-none opacity-20 z-0">
        <div className="absolute top-0 right-0 w-[50%] h-[50%] bg-primary/5 blur-[120px] rounded-full translate-x-1/2 -translate-y-1/2" />
        <div className="absolute bottom-0 left-0 w-[50%] h-[50%] bg-primary/2 blur-[120px] rounded-full -translate-x-1/2 translate-y-1/2" />
      </div>

      {/* Navigation */}
      <nav className="h-24 flex items-center relative z-10">
        <div className="max-w-[1100px] mx-auto px-6 w-full">
          <Link href="/" className="group flex items-center gap-2 w-fit">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center shadow-lg shadow-primary/20 group-hover:scale-105 transition-all">
               <Sparkles className="w-5 h-5 text-black" />
            </div>
            <span className="text-xl font-bold tracking-tighter text-white group-hover:text-primary transition-colors">WORTH</span>
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main className="max-w-[760px] mx-auto px-6 pt-12 pb-40 relative z-10">
        <header className="mb-20">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-primary/10 border border-primary/20 rounded-full mb-6">
            <div className="w-1 h-1 rounded-full bg-primary animate-pulse" />
            <span className="text-[10px] font-bold text-primary uppercase tracking-[0.2em]">Legal Document</span>
          </div>
          <h1 className="text-5xl md:text-6xl font-bold tracking-tight text-white mb-6 leading-[1.1]">Terms of Service</h1>
          <p className="text-secondary font-medium uppercase tracking-[0.2em] text-xs opacity-60">Last updated: March 28, 2026</p>
        </header>

        <div className="space-y-16">
          <section className="group">
            <h2 className="text-xl font-bold text-primary uppercase tracking-[0.2em] mb-6 flex items-center gap-3">
              <span className="text-xs opacity-30 text-white font-black shrink-0">01.</span>
              Acceptance of Terms
            </h2>
            <p className="text-lg leading-[1.8] text-secondary/90 font-medium">
              By accessing or using WorthAI, you agree to be bound by these Terms of Service. If you do not agree, please do not use our service. This agreement governs your interaction with our tools, advice engines, and data collection.
            </p>
          </section>

          <section className="group">
            <h2 className="text-xl font-bold text-primary uppercase tracking-[0.2em] mb-6 flex items-center gap-3">
              <span className="text-xs opacity-30 text-white font-black shrink-0">02.</span>
              Description of Service
            </h2>
            <p className="text-lg leading-[1.8] text-secondary/90 font-medium">
              WorthAI is an AI-powered personal finance advisor that provides general financial guidance based on information you provide. WorthAI is not a licensed financial advisor and does not provide professional financial, legal, or investment advice.
            </p>
          </section>

          <section className="group">
            <h2 className="text-xl font-bold text-primary uppercase tracking-[0.2em] mb-6 flex items-center gap-3">
              <span className="text-xs opacity-30 text-white font-black shrink-0">03.</span>
              Not Financial Advice
            </h2>
            <p className="text-lg leading-[1.8] text-secondary/90 font-medium bg-primary/5 p-8 rounded-2xl border border-primary/20 italic">
              All content generated by WorthAI is for informational purposes only. You should consult a qualified financial advisor before making any significant financial decisions. WorthAI is not responsible for any financial decisions made based on its suggestions.
            </p>
          </section>

          <section className="group">
            <h2 className="text-xl font-bold text-primary uppercase tracking-[0.2em] mb-6 flex items-center gap-3">
              <span className="text-xs opacity-30 text-white font-black shrink-0">04.</span>
              User Responsibilities
            </h2>
            <p className="text-lg leading-[1.8] text-secondary/90 font-medium">
              You are responsible for the accuracy of the financial information you provide. You must be 18 years or older to use WorthAI. You agree not to misuse the service or attempt to access other users&apos; data or proprietary code.
            </p>
          </section>

          <section className="group">
            <h2 className="text-xl font-bold text-primary uppercase tracking-[0.2em] mb-6 flex items-center gap-3">
              <span className="text-xs opacity-30 text-white font-black shrink-0">05.</span>
              Limitation of Liability
            </h2>
            <p className="text-lg leading-[1.8] text-secondary/90 font-medium font-josefin">
              WorthAI and its creators are not liable for any financial losses, damages, or consequences arising from use of this service. Use WorthAI at your own risk. We provide the service &quot;as is&quot; without explicit warranties of any kind.
            </p>
          </section>

          <section className="group">
            <h2 className="text-xl font-bold text-primary uppercase tracking-[0.2em] mb-6 flex items-center gap-3">
              <span className="text-xs opacity-30 text-white font-black shrink-0">06.</span>
              Changes to Terms
            </h2>
            <p className="text-lg leading-[1.8] text-secondary/90 font-medium">
              We reserve the right to update these terms at any time. Continued use of WorthAI after changes constitutes acceptance of the new terms. We suggest reviewing this page periodically.
            </p>
          </section>

          <section className="group">
            <h2 className="text-xl font-bold text-primary uppercase tracking-[0.2em] mb-6 flex items-center gap-3">
              <span className="text-xs opacity-30 text-white font-black shrink-0">07.</span>
              Contact
            </h2>
            <p className="text-lg leading-[1.8] text-secondary/90 font-medium">
              For questions about these terms, contact our legal team at <a href="mailto:worthai.support@gmail.com" className="text-primary hover:underline underline-offset-4 decoration-primary/30 transition-all font-bold">worthai.support@gmail.com</a>
            </p>
          </section>
        </div>

        <div className="mt-32 pt-12 border-t border-white/10 flex flex-col md:flex-row justify-between items-center gap-8 translate-z-0">
           <Link href="/" className="inline-flex items-center gap-2 text-secondary hover:text-primary transition-all group font-bold">
              <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
              Back to home
           </Link>
           <span className="text-[10px] text-secondary/30 uppercase tracking-[0.4em] font-bold">WORTH AI &nbsp; | &nbsp; 2026</span>
        </div>
      </main>
    </div>
  )
}
